<figure>
<center>
<img src='https://www.economicas.uba.ar/wp-content/uploads/2020/08/cropped-logo_FCE.png' />
</figure>

# **Universidad de Buenos Aires**
## **Facultad de Ciencias Económicas**

### **Taller de Programación para el Análisis de Datos**

#### **Clase 7.1: Obtención de tabla de datos de un pdf**

En esta clase veremos como extraer una tabla de datos que esté contenida en un archivo pdf con Python en Colab

NOTA: solo esposible extraer tablas que estén creadas como objeto en el documento (por ejemplo, si son una imágen insertada no son posibles de extraer)

### **Librería**

In [1]:
#se instala el módulo
!pip install "camelot-py[cv]"

Collecting camelot-py[cv]
  Downloading camelot_py-1.0.9-py3-none-any.whl.metadata (9.8 kB)
WARNING: camelot-py 1.0.9 does not provide the extra 'cv'
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (8.3.2)
Requirement already satisfied: chardet>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: numpy>=1.26.1 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (2.0.2)
Requirement already satisfied: openpyxl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (3.1.5)
Collecting pdfminer-six>=20240706 (from camelot-py[cv])
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting pypdf<6.0,>=4.0 (from camelot-py[cv])
  Downloading pypdf-5.9.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: pandas>=2.2.2 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (2.2.2)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: opencv-python-headless>=4.7.0.68 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (4.13.0.92)
Collecting pypdfium2>=4 (from camelot-py[cv])
  Downloading pypdfium2-5.7.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: pillow>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from camelot-py[cv]) (11.3.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->camelot-py[cv]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->camelot-py[cv]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.2->camelot-py[cv]) (2026.1)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer-six>=20240706->camelot-py[cv]) (3.4.7)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer-six>=20240706->camelot-py[cv]) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py[cv]) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv]) (3.0)
Downloading pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 47.7 MB/s eta 0:00:0000:0100:01
Downloading pypdf-5.9.0-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.2/313.2 kB 21.3 MB/s eta 0:00:00
Downloading pypdfium2-5.7.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 68.0 MB/s eta 0:00:00:00:01
Downloading camelot_py-1.0.9-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 5.1 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pypdf, pdfminer-six, camelot-py
Successfully installed camelot-py-1.0.9 pdfminer-six-20260107 pypdf-5.9.0 pypdfium2-5.7.1

In [2]:
#se carga la librería
import camelot

### **Ejemplo 1**

Obtenemos un pdf para extraer una tabla de datos.

Este lo puede imprtar directamente al colab o descargarlo desde la web.

Como ejemplo, utilizaremos una descarga directa desde la web: https://www.bcra.gob.ar/PublicacionesEstadisticas/informe-inclusion-financiera-012025.asp

Entrando al link, a la derecha encuentra "descargar versión PDF"-> clcik derecho "copiar enlace"

Luego, abra el pdf haciendo directamente click para ver que tabla quiere extraer. Para el ejemplo, elegimos la que se encuentra en la página 5 "Tabla de indicadores | Inclusión financiera en Argentina"

In [3]:
#se descarga un pdf desde la web

!wget --no-check-certificate https://www.bcra.gob.ar/Pdfs/PublicacionesEstadisticas/Informe-inclusion-financiera-octubre-25.pdf

--2026-04-21 15:18:21--  https://www.bcra.gob.ar/Pdfs/PublicacionesEstadisticas/Informe-inclusion-financiera-octubre-25.pdf
Resolving www.bcra.gob.ar (www.bcra.gob.ar)... 3.171.171.79, 3.171.171.7, 3.171.171.11, ...
Connecting to www.bcra.gob.ar (www.bcra.gob.ar)|3.171.171.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.bcra.gob.ar/archivos/Pdfs/PublicacionesEstadisticas/Informe-inclusion-financiera-octubre-25.pdf [following]
--2026-04-21 15:18:22--  https://www.bcra.gob.ar/archivos/Pdfs/PublicacionesEstadisticas/Informe-inclusion-financiera-octubre-25.pdf
Reusing existing connection to www.bcra.gob.ar:443.
HTTP request sent, awaiting response... 200 OK
Length: 2404631 (2.3M) [application/pdf]
Saving to: ‘Informe-inclusion-financiera-octubre-25.pdf’

Informe-inclusion-f 100%[===================>]   2.29M  2.92MB/s    in 0.8s

2026-04-21 15:18:23 (2.92 MB/s) - ‘Informe-inclusion-financiera-octubre-25.pdf’ saved [2404631/2404631]

In [4]:
#se crea un dataframe con la tabla de datos extraída del pdf
tables = camelot.read_pdf('/content/Informe-inclusion-financiera-octubre-25.pdf', pages="5", flavor="stream", suppress_stdout=True)

In [5]:
#se observa la tabla extraída
df1=tables[0].df
df1

,0,1,2,3,4
0,,último,,,
1,Indicador,,dic-23,dic-24,jun-25
2,,dato,,,
3,Puntos de acceso cada 10.000 adultos,jun-25 (1),"14,5","14,0","14,0"
4,Porcentaje de localidades con al menos un punt...,jun-25 (1),"45,9","46,2","46,3"
5,Porcentaje de la población adulta en localidad...,jun-25 (1),"94,1","94,2","94,1"
6,Población adulta con cuenta (en millones),jun-25,"36,3","37,2","37,5"
7,Población adulta con cuenta bancaria (en millo...,jun-25,"34,8","35,3","35,6"
8,Población adulta con cuenta de pago (en millones),jun-25,"23,8","27,4","28,9"
9,Cantidad de pagos con medios electrónicos por ...,jun-25 (2),"16,6","25,0","28,4"
10,Cantidad de transferencias electrónicas por ad...,jun-25 (2),"5,8","12,2","15,2"
11,Cantidad de Pagos con Transferencia por adulto,jun-25 (2),"0,8","1,2","1,7"
12,Cantidad de pagos con tarjetas por adulto,jun-25 (2),"9,0","10,4","10,1"
13,Cantidad de extracciones de efectivo por adulto,jun-25 (2),"2,7","2,8","1,9"
14,Porcentaje de cuentahabientes con débitos en l...,jun-25,"65,6","73,5","75,5"
15,Cantidad de plazos fijos cada 100 cuentahabita...,jun-25,"16,6","10,6","11,5"
16,Porcentaje de adultos con crédito en el sistem...,jun-25 (3),"55,3","50,1","52,6"
17,Porcentaje de adultos con crédito en EEFF,jun-25 (3),"38,6","37,5","39,3"
18,Porcentaje de adultos con crédito en PNFC,jun-25 (3),"29,2","26,3","29,1"
19,Cantidad de MiPyMEs con financiamiento en el S...,jun-25 (3),"1,4","1,4","1,4"

Resulta necesario formatear los datos para estructurarlos y poder convertirlos en DataFrame, siendo el objeto operable con Python

In [6]:
#se borran las filas 0 (primera) y 2 (tercera)
df2=df1.drop([0,2], axis=0)
df2.reset_index(drop=True, inplace=True)
df2

,0,1,2,3,4
0,Indicador,,dic-23,dic-24,jun-25
1,Puntos de acceso cada 10.000 adultos,jun-25 (1),"14,5","14,0","14,0"
2,Porcentaje de localidades con al menos un punt...,jun-25 (1),"45,9","46,2","46,3"
3,Porcentaje de la población adulta en localidad...,jun-25 (1),"94,1","94,2","94,1"
4,Población adulta con cuenta (en millones),jun-25,"36,3","37,2","37,5"
5,Población adulta con cuenta bancaria (en millo...,jun-25,"34,8","35,3","35,6"
6,Población adulta con cuenta de pago (en millones),jun-25,"23,8","27,4","28,9"
7,Cantidad de pagos con medios electrónicos por ...,jun-25 (2),"16,6","25,0","28,4"
8,Cantidad de transferencias electrónicas por ad...,jun-25 (2),"5,8","12,2","15,2"
9,Cantidad de Pagos con Transferencia por adulto,jun-25 (2),"0,8","1,2","1,7"
10,Cantidad de pagos con tarjetas por adulto,jun-25 (2),"9,0","10,4","10,1"
11,Cantidad de extracciones de efectivo por adulto,jun-25 (2),"2,7","2,8","1,9"
12,Porcentaje de cuentahabientes con débitos en l...,jun-25,"65,6","73,5","75,5"
13,Cantidad de plazos fijos cada 100 cuentahabita...,jun-25,"16,6","10,6","11,5"
14,Porcentaje de adultos con crédito en el sistem...,jun-25 (3),"55,3","50,1","52,6"
15,Porcentaje de adultos con crédito en EEFF,jun-25 (3),"38,6","37,5","39,3"
16,Porcentaje de adultos con crédito en PNFC,jun-25 (3),"29,2","26,3","29,1"
17,Cantidad de MiPyMEs con financiamiento en el S...,jun-25 (3),"1,4","1,4","1,4"

In [7]:
#borrar  columna 1 (segunda)
df2=df2.drop([1], axis=1)
df2.reset_index(drop=True, inplace=True)
df2

                                                    0       2       3       4
0                                           Indicador  dic-23  dic-24  jun-25
1                Puntos de acceso cada 10.000 adultos    14,5    14,0    14,0
2   Porcentaje de localidades con al menos un punt...    45,9    46,2    46,3
3   Porcentaje de la población adulta en localidad...    94,1    94,2    94,1
4           Población adulta con cuenta (en millones)    36,3    37,2    37,5
5   Población adulta con cuenta bancaria (en millo...    34,8    35,3    35,6
6   Población adulta con cuenta de pago (en millones)    23,8    27,4    28,9
7   Cantidad de pagos con medios electrónicos por ...    16,6    25,0    28,4
8   Cantidad de transferencias electrónicas por ad...     5,8    12,2    15,2
9      Cantidad de Pagos con Transferencia por adulto     0,8     1,2     1,7
10          Cantidad de pagos con tarjetas por adulto     9,0    10,4    10,1
11    Cantidad de extracciones de efectivo por adulto     2,7     2,8     1,9
12  Porcentaje de cuentahabientes con débitos en l...    65,6    73,5    75,5
13  Cantidad de plazos fijos cada 100 cuentahabita...    16,6    10,6    11,5
14  Porcentaje de adultos con crédito en el sistem...    55,3    50,1    52,6
15          Porcentaje de adultos con crédito en EEFF    38,6    37,5    39,3
16          Porcentaje de adultos con crédito en PNFC    29,2    26,3    29,1
17  Cantidad de MiPyMEs con financiamiento en el S...     1,4     1,4     1,4

In [8]:
#reemplazar nombres de columnas por la primer fila

df2=df2.rename(columns=df2.iloc[0]).drop(df2.index[0])
df2.reset_index(drop=True, inplace=True)
df2

                                            Indicador dic-23 dic-24 jun-25
0                Puntos de acceso cada 10.000 adultos   14,5   14,0   14,0
1   Porcentaje de localidades con al menos un punt...   45,9   46,2   46,3
2   Porcentaje de la población adulta en localidad...   94,1   94,2   94,1
3           Población adulta con cuenta (en millones)   36,3   37,2   37,5
4   Población adulta con cuenta bancaria (en millo...   34,8   35,3   35,6
5   Población adulta con cuenta de pago (en millones)   23,8   27,4   28,9
6   Cantidad de pagos con medios electrónicos por ...   16,6   25,0   28,4
7   Cantidad de transferencias electrónicas por ad...    5,8   12,2   15,2
8      Cantidad de Pagos con Transferencia por adulto    0,8    1,2    1,7
9           Cantidad de pagos con tarjetas por adulto    9,0   10,4   10,1
10    Cantidad de extracciones de efectivo por adulto    2,7    2,8    1,9
11  Porcentaje de cuentahabientes con débitos en l...   65,6   73,5   75,5
12  Cantidad de plazos fijos cada 100 cuentahabita...   16,6   10,6   11,5
13  Porcentaje de adultos con crédito en el sistem...   55,3   50,1   52,6
14          Porcentaje de adultos con crédito en EEFF   38,6   37,5   39,3
15          Porcentaje de adultos con crédito en PNFC   29,2   26,3   29,1
16  Cantidad de MiPyMEs con financiamiento en el S...    1,4    1,4    1,4

In [9]:
df2.dtypes

Indicador    object
dic-23       object
dic-24       object
jun-25       object
dtype: object

al observar que las columnas 1, 2 y 3 las esta leyendo como string, entonces las convertimos a numéricas

pero observamos que el el separador de decimal es una coma. Entonces debemos reemplazarla por un punto y al mismo tiempo podemos definir el formato

In [10]:
df2.columns

Index(['Indicador', 'dic-23', 'dic-24', 'jun-25'], dtype='object')

In [11]:
#reemplazmaos la como por punto
for j in df2.columns:
  df2[j]=df2[j].str.replace(',','.')

In [12]:
df2

                                            Indicador dic-23 dic-24 jun-25
0                Puntos de acceso cada 10.000 adultos   14.5   14.0   14.0
1   Porcentaje de localidades con al menos un punt...   45.9   46.2   46.3
2   Porcentaje de la población adulta en localidad...   94.1   94.2   94.1
3           Población adulta con cuenta (en millones)   36.3   37.2   37.5
4   Población adulta con cuenta bancaria (en millo...   34.8   35.3   35.6
5   Población adulta con cuenta de pago (en millones)   23.8   27.4   28.9
6   Cantidad de pagos con medios electrónicos por ...   16.6   25.0   28.4
7   Cantidad de transferencias electrónicas por ad...    5.8   12.2   15.2
8      Cantidad de Pagos con Transferencia por adulto    0.8    1.2    1.7
9           Cantidad de pagos con tarjetas por adulto    9.0   10.4   10.1
10    Cantidad de extracciones de efectivo por adulto    2.7    2.8    1.9
11  Porcentaje de cuentahabientes con débitos en l...   65.6   73.5   75.5
12  Cantidad de plazos fijos cada 100 cuentahabita...   16.6   10.6   11.5
13  Porcentaje de adultos con crédito en el sistem...   55.3   50.1   52.6
14          Porcentaje de adultos con crédito en EEFF   38.6   37.5   39.3
15          Porcentaje de adultos con crédito en PNFC   29.2   26.3   29.1
16  Cantidad de MiPyMEs con financiamiento en el S...    1.4    1.4    1.4

In [13]:
df2.dtypes

Indicador    object
dic-23       object
dic-24       object
jun-25       object
dtype: object

In [14]:
#cambiamos a tipo float las columnas correspondientes
for i in df2.columns:
  if i!='Indicador':
    df2[i]=df2[i].astype(float)

In [15]:
df2.dtypes

Indicador     object
dic-23       float64
dic-24       float64
jun-25       float64
dtype: object

### **Ejemplo 2**

In [16]:
#se descarga un pdf desde la web

!wget --no-check-certificate https://www.bcra.gob.ar/Pdfs/PublicacionesEstadisticas/IIF-primer-semestre-2022.pdf

--2026-04-21 15:19:23--  https://www.bcra.gob.ar/Pdfs/PublicacionesEstadisticas/IIF-primer-semestre-2022.pdf
Resolving www.bcra.gob.ar (www.bcra.gob.ar)... 3.171.171.79, 3.171.171.102, 3.171.171.11, ...
Connecting to www.bcra.gob.ar (www.bcra.gob.ar)|3.171.171.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.bcra.gob.ar/archivos/Pdfs/PublicacionesEstadisticas/IIF-primer-semestre-2022.pdf [following]
--2026-04-21 15:19:23--  https://www.bcra.gob.ar/archivos/Pdfs/PublicacionesEstadisticas/IIF-primer-semestre-2022.pdf
Reusing existing connection to www.bcra.gob.ar:443.
HTTP request sent, awaiting response... 200 OK
Length: 1249557 (1.2M) [application/pdf]
Saving to: ‘IIF-primer-semestre-2022.pdf’

IIF-primer-semestre 100%[===================>]   1.19M  1.82MB/s    in 0.7s

2026-04-21 15:19:25 (1.82 MB/s) - ‘IIF-primer-semestre-2022.pdf’ saved [1249557/1249557]

In [17]:
#se crea una tabla con la tabla de datos extraída del pdf
table2 = camelot.read_pdf('/content/IIF-primer-semestre-2022.pdf', pages="7", flavor="stream", suppress_stdout=True)

In [18]:
#se observa la tabla extraída
df12=table2[0].df
df12

,0,1,2,3,4,5,6,7,8,9
0,Tabla de indicadores | Inclusión financiera en...,,,,,,,,,
1,,,último,,,,,,,
2,,Indicador,,2016,2017,2018,2019,2020,2021,2022
3,,,dato,,,,,,,
4,,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
5,Infraestructura,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
6,,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
7,,Porcentaje de adultos que viven en localidades...,,,,,,,,
8,,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
9,,un PDA,,,,,,,,
10,,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
11,,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
12,,Porcentaje de la población adulta con al menos...,,,,,,,,
13,,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
14,,(mujeres),,,,,,,,
15,,Porcentaje de la población adulta con al menos...,,,,,,,,
16,Cuentas,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
17,,(hombres),,,,,,,,
18,,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
19,,Porcentaje de la población adulta con al menos...,,,,,,,,
20,,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
21,,(mujeres),,,,,,,,
22,,Porcentaje de la población adulta con al menos...,,,,,,,,
23,,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
24,,(hombres),,,,,,,,
25,,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
26,,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
27,Transacciones,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
28,,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
29,,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
30,,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
31,Ahorro,Cantidad de plazos fijos cada 100 cuentahabita...,,,,,,,,
32,,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
33,,($/UVA/USD),,,,,,,,
34,,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
35,,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
36,,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
37,Créditos,Porcentaje de adultos con crédito en el sistem...,,,,,,,,
38,,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
39,,ampliado (SFA),,,,,,,,
40,,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
41,,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [19]:
#se borran las dos primeras y la cuarta fila
df22=df12.drop([0,1,3], axis=0)
df22.reset_index(drop=True, inplace=True)
df22

,0,1,2,3,4,5,6,7,8,9
0,,Indicador,,2016,2017,2018,2019,2020,2021,2022
1,,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
2,Infraestructura,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
3,,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
4,,Porcentaje de adultos que viven en localidades...,,,,,,,,
5,,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
6,,un PDA,,,,,,,,
7,,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
8,,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
9,,Porcentaje de la población adulta con al menos...,,,,,,,,
10,,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
11,,(mujeres),,,,,,,,
12,,Porcentaje de la población adulta con al menos...,,,,,,,,
13,Cuentas,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
14,,(hombres),,,,,,,,
15,,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
16,,Porcentaje de la población adulta con al menos...,,,,,,,,
17,,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
18,,(mujeres),,,,,,,,
19,,Porcentaje de la población adulta con al menos...,,,,,,,,
20,,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
21,,(hombres),,,,,,,,
22,,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
23,,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
24,Transacciones,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
25,,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
26,,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
27,,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
28,Ahorro,Cantidad de plazos fijos cada 100 cuentahabita...,,,,,,,,
29,,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
30,,($/UVA/USD),,,,,,,,
31,,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
32,,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
33,,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
34,Créditos,Porcentaje de adultos con crédito en el sistem...,,,,,,,,
35,,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
36,,ampliado (SFA),,,,,,,,
37,,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
38,,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [20]:
#borrar primer columna
df22=df22.drop([0], axis=1)
df22.reset_index(drop=True, inplace=True)
df22

,1,2,3,4,5,6,7,8,9
0,Indicador,,2016,2017,2018,2019,2020,2021,2022
1,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
2,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
3,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
4,Porcentaje de adultos que viven en localidades...,,,,,,,,
5,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
6,un PDA,,,,,,,,
7,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
8,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
9,Porcentaje de la población adulta con al menos...,,,,,,,,
10,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
11,(mujeres),,,,,,,,
12,Porcentaje de la población adulta con al menos...,,,,,,,,
13,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
14,(hombres),,,,,,,,
15,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
16,Porcentaje de la población adulta con al menos...,,,,,,,,
17,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
18,(mujeres),,,,,,,,
19,Porcentaje de la población adulta con al menos...,,,,,,,,
20,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
21,(hombres),,,,,,,,
22,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
23,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
24,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
25,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
26,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
27,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
28,Cantidad de plazos fijos cada 100 cuentahabita...,,,,,,,,
29,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
30,($/UVA/USD),,,,,,,,
31,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
32,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
33,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
34,Porcentaje de adultos con crédito en el sistem...,,,,,,,,
35,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
36,ampliado (SFA),,,,,,,,
37,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
38,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [21]:
#reemplazar nombres de columnas por la primer fila

df22=df22.rename(columns=df22.iloc[0]).drop(df22.index[0])
df22.reset_index(drop=True, inplace=True)
df22

,Indicador,,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,,,,,,,,
4,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
5,un PDA,,,,,,,,
6,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
8,Porcentaje de la población adulta con al menos...,,,,,,,,
9,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
10,(mujeres),,,,,,,,
11,Porcentaje de la población adulta con al menos...,,,,,,,,
12,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
13,(hombres),,,,,,,,
14,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
15,Porcentaje de la población adulta con al menos...,,,,,,,,
16,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
17,(mujeres),,,,,,,,
18,Porcentaje de la población adulta con al menos...,,,,,,,,
19,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
20,(hombres),,,,,,,,
21,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
22,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
23,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
24,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
25,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
26,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
27,Cantidad de plazos fijos cada 100 cuentahabita...,,,,,,,,
28,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
29,($/UVA/USD),,,,,,,,
30,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
31,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
32,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
33,Porcentaje de adultos con crédito en el sistem...,,,,,,,,
34,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
35,ampliado (SFA),,,,,,,,
36,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
37,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [22]:
#agregación de nombre a columna donde está el período
df33 = df22.rename(columns={'':'Dato'})
df33

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,,,,,,,,
4,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
5,un PDA,,,,,,,,
6,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
8,Porcentaje de la población adulta con al menos...,,,,,,,,
9,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
10,(mujeres),,,,,,,,
11,Porcentaje de la población adulta con al menos...,,,,,,,,
12,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
13,(hombres),,,,,,,,
14,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
15,Porcentaje de la población adulta con al menos...,,,,,,,,
16,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
17,(mujeres),,,,,,,,
18,Porcentaje de la población adulta con al menos...,,,,,,,,
19,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
20,(hombres),,,,,,,,
21,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
22,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
23,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
24,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
25,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
26,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
27,Cantidad de plazos fijos cada 100 cuentahabita...,,,,,,,,
28,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
29,($/UVA/USD),,,,,,,,
30,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
31,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
32,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
33,Porcentaje de adultos con crédito en el sistem...,,,,,,,,
34,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
35,ampliado (SFA),,,,,,,,
36,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
37,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [23]:
#se reemplazan los valores vacíos por los de la fila correspondiente
import numpy as np
nans=df33.loc[3].isin(('', ' ', 'nan', np.nan))
df33.loc[3][nans] = df33.loc[4]
df33.loc[8][nans] = df33.loc[9]
df33.loc[11][nans] = df33.loc[12]
df33.loc[15][nans] = df33.loc[16]
df33.loc[18][nans] = df33.loc[19]
df33.loc[27][nans] = df33.loc[28]
df33.loc[33][nans] = df33.loc[34]
df33

/tmp/ipykernel_53061/384693534.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[3][nans] = df33.loc[4]
/tmp/ipykernel_53061/384693534.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[8][nans] = df33.loc[9]
/tmp/ipykernel_53061/384693534.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[11][nans] = df33.loc[12]
/tmp/ipykernel_53061/384693534.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[15][nans] = df33.loc[16]
/tmp/ipykernel_53061/384693534.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[18][nans] = df33.loc[19]
/tmp/ipykernel_53061/384693534.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[27][nans] = df33.loc[28]
/tmp/ipykernel_53061/384693534.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df33.loc[33][nans] = df33.loc[34]

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
4,,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
5,un PDA,,,,,,,,
6,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
8,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
9,,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
10,(mujeres),,,,,,,,
11,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
12,,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
13,(hombres),,,,,,,,
14,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
15,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
16,,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
17,(mujeres),,,,,,,,
18,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
19,,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
20,(hombres),,,,,,,,
21,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
22,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
23,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
24,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
25,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
26,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
27,Cantidad de plazos fijos cada 100 cuentahabita...,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
28,,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
29,($/UVA/USD),,,,,,,,
30,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
31,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
32,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
33,Porcentaje de adultos con crédito en el sistem...,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
34,,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
35,ampliado (SFA),,,,,,,,
36,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
37,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [24]:
#se borran las filas ya utilizadas

df4=df33.drop([4,9,12,16,19,28,34], axis=0)
df4.reset_index(drop=True, inplace=True)
df4

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
4,un PDA,,,,,,,,
5,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
6,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
8,(mujeres),,,,,,,,
9,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
10,(hombres),,,,,,,,
11,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
12,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
13,(mujeres),,,,,,,,
14,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
15,(hombres),,,,,,,,
16,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
17,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
18,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
19,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
20,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
21,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
22,Cantidad de plazos fijos cada 100 cuentahabita...,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
23,($/UVA/USD),,,,,,,,
24,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
25,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
26,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
27,Porcentaje de adultos con crédito en el sistem...,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
28,ampliado (SFA),,,,,,,,
29,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
30,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [25]:
df4.iloc[3,0]

'Porcentaje de adultos que viven en localidades con al menos'

In [26]:
#se concatenan los texto por filas
df4.iloc[3,0] = df4.iloc[3,0] + ' ' + df4.iloc[4,0]
df4.iloc[7,0] = df4.iloc[7,0] + ' ' + df4.iloc[8,0]
df4.iloc[9,0] = df4.iloc[9,0] + ' ' + df4.iloc[10,0]
df4.iloc[12,0] = df4.iloc[12,0] + ' ' + df4.iloc[13,0]
df4.iloc[14,0] = df4.iloc[14,0] + ' ' + df4.iloc[15,0]
df4.iloc[22,0] = df4.iloc[22,0] + ' ' + df4.iloc[23,0]
df4.iloc[27,0] = df4.iloc[27,0] + ' ' + df4.iloc[28,0]
df4

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
4,un PDA,,,,,,,,
5,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
6,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
8,(mujeres),,,,,,,,
9,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
10,(hombres),,,,,,,,
11,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
12,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
13,(mujeres),,,,,,,,
14,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
15,(hombres),,,,,,,,
16,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
17,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
18,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
19,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
20,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
21,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
22,Cantidad de plazos fijos cada 100 cuentahabita...,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
23,($/UVA/USD),,,,,,,,
24,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
25,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
26,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
27,Porcentaje de adultos con crédito en el sistem...,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
28,ampliado (SFA),,,,,,,,
29,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
30,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [27]:
#se verifica individualmente, por ejemplo
df4.iloc[27,0]

'Porcentaje de adultos con crédito en el sistema financiero ampliado (SFA)'

In [28]:
#se borran las filas ya utilizadas
df5=df4.drop([4,8,10,13,15,23,28], axis=0)
df5.reset_index(drop=True, inplace=True)
df5

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22 (1),25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22 (1),"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22 (1),"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,jun-22 (1),"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
4,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
5,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
6,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
8,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
9,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
10,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
11,Cantidad de pagos con tarjetas de débito por a...,jun-22 (2),"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
12,Cantidad de pagos con tarjetas de crédito por ...,jun-22 (2),"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
13,Cantidad de transferencias originadas en CBU p...,jun-22 (2),"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
14,Cantidad de transferencias originadas en CVU p...,jun-22 (2),-,-,-,-,"0,1","0,6","0,9"
15,Cantidad de extracciones de efectivo por ATM p...,jun-22 (2),"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
16,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
17,Cantidad de plazos fijos cada 100 cuentahabita...,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
18,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
19,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
20,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
21,Porcentaje de adultos con crédito en el sistem...,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
22,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
23,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

In [29]:
df5.iloc[:,1].unique()

array(['jun-22 (1)', 'jun-22', 'jun-22 (2)'], dtype=object)

In [30]:
#se normaliza la columna Dato
df5['Dato']='jun-22'

In [31]:
#Tabla final
df5

,Indicador,Dato,2016,2017,2018,2019,2020,2021,2022
0,Puntos de acceso a servicios financieros,jun-22,25.306,26.553,29.050,30.726,44.454,50.270,53.912
1,Puntos de acceso cada 10.000 adultos,jun-22,"7,7","8,0","8,6","9,0","12,9","14,4","15,3"
2,Porcentaje de localidades con al menos un punt...,jun-22,"39,6%","40,7%","41,4%","41,9%","47,0%","52,3%","52,3%"
3,Porcentaje de adultos que viven en localidades...,jun-22,"91,0%","91,2%","91,2%","91,3%","92,1%","92,5%","92,5%"
4,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"82,7%","92,9%","95,2%","98,5%"
5,Porcentaje de la población adulta con al menos...,jun-22,-,"77,9%","80,4%","81,5%","90,7%","91,3%","95,2%"
6,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,7%","85,2%","90,9%","91,8%","95,5%"
7,Porcentaje de la población adulta con al menos...,jun-22,-,-,"80,1%","77,6%","90,5%","90,8%","94,8%"
8,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"6,8%","24,1%","46,7%","50,5%"
9,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"5,3%","23,2%","47,4%","50,8%"
10,Porcentaje de la población adulta con al menos...,jun-22,-,-,-,"8,4%","25,1%","45,9%","50,1%"
11,Cantidad de pagos con tarjetas de débito por a...,jun-22,"1,7","1,9","2,2","2,6","3,0","4,1","4,7"
12,Cantidad de pagos con tarjetas de crédito por ...,jun-22,"2,1","2,2","2,3","2,4","2,1","2,4","2,4"
13,Cantidad de transferencias originadas en CBU p...,jun-22,"0,2","0,2","0,3","0,4","0,8","1,3","2,0"
14,Cantidad de transferencias originadas en CVU p...,jun-22,-,-,-,-,"0,1","0,6","0,9"
15,Cantidad de extracciones de efectivo por ATM p...,jun-22,"2,3","2,6","2,7","2,9","2,7","2,7","2,6"
16,Cantidad de plazos fijos cada 10.000 adultos (...,jun-22,759,771,925,841,908,985,1.300
17,Cantidad de plazos fijos cada 100 cuentahabita...,jun-22,-,-,-,"11,0","10,6","11,3","14,2"
18,Porcentaje de adultos con crédito en entidades...,jun-22,"36,0%","37,3%","37,9%","37,0%","35,4%","35,2%","35,6%"
19,Porcentaje de mujeres con crédito en entidades...,jun-22,"34,0%","35,0%","35,8%","35,3%","33,6%","33,4%","34,1%"
20,Porcentaje de hombres con crédito en entidades...,jun-22,"39,3%","39,7%","40,0%","38,8%","37,3%","37,0%","37,2%"
21,Porcentaje de adultos con crédito en el sistem...,jun-22,"49,0%","49,9%","50,5%","49,7%","47,8%","51,1%","53,3%"
22,Porcentaje de mujeres con crédito en el SFA,jun-22,"45,0%","46,6%","47,3%","46,6%","45,0%","49,0%","51,4%"
23,Porcentaje de hombres con crédito en el SFA,jun-22,"53,2%","53,3%","53,7%","52,7%","50,6%","53,2%","55,0%"

Es una tabla y no un dataframe operativo por el tipo de dato. Puede:
- quitar el simbolo de porcentaje, reemplzar la coma por punto y convertir a float (en base a lo hecho en el ejemplo 1) de forma tal que sean numeros operables
- exportarla como está y utilizarla en algún documento
- extraer valores de interés puntualmente

### **Leer un word y extraer tabla de datos**

Por ejemplo descargamos el Anuario 2023: https://www.argentina.gob.ar/educacion/universidades/informacion/publicaciones/anuarios

In [32]:
!wget https://www.argentina.gob.ar/sites/default/files/rv_anuario_finales_todos.zip

--2026-04-21 15:21:05--  https://www.argentina.gob.ar/sites/default/files/rv_anuario_finales_todos.zip
Resolving www.argentina.gob.ar (www.argentina.gob.ar)... 172.67.75.35, 104.26.4.183, 104.26.5.183, ...
Connecting to www.argentina.gob.ar (www.argentina.gob.ar)|172.67.75.35|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8464271 (8.1M) [application/zip]
Saving to: ‘rv_anuario_finales_todos.zip’

rv_anuario_finales_ 100%[===================>]   8.07M  6.71MB/s    in 1.2s

2026-04-21 15:21:07 (6.71 MB/s) - ‘rv_anuario_finales_todos.zip’ saved [8464271/8464271]

In [33]:
!unzip /content/rv_anuario_finales_todos.zip

Archive:  /content/rv_anuario_finales_todos.zip
 extracting: 0.1 Introduccio╠Бn 2023.docx
 extracting: 1.1 Datos Generales 2023.xlsx
 extracting: 1.2 Indicadores 2023.xlsx
 extracting: 2.1 Pregrado y Grado Gesti├│n Estatal 2023.xlsx
 extracting: 2.2 Pregrado y Grado Gesti├│n Privada 2023.xlsx
 extracting: 3.1 Posgrado Gestio╠Бn Estatal 2023.xlsx
 extracting: 3.2 Posgrado Gesti├│n Privada 2023.xlsx
 extracting: 4. RHUN.xlsx
  inflating: 5. Presupuesto 2023.xls
 extracting: 6.1 Direcci├│n Nacional de Programas de Calidad, Ciencia y Vinculaci├│n Tecnol├│gica 2023.docx
 extracting: 6.1 SSPU - Direcci├│n Nacional de Programas de Calidad, Ciencia y Vinculaci├│n Tecnol├│gica 2023 - Anexo.xlsx
 extracting: 6.1.1 Programa de Calidad Universitaria 2023.docx
 extracting: 6.1.2 Programa de Ciencia, Tecnolog├нa y Vinculaci├│n Tecnol├│gica 2023.docx
 extracting: 6.1.3 Secretar├нa Ejecutiva de los Consejos Regionales de Planificaci├│n de la Educaci├│n Superior 2023.docx
 extracting: 6.1.4 Incentivos a los docentes investigadores 2023.docx
 extracting: 6.1.5 Argentina Investiga 2023.docx
 extracting: 6.1.6 Programa para la Investigaci├│n Universitaria Argentina 2023.docx
 extracting: 6.2 PIESCI 2023 - L├нneas Program├бticas.docx
 extracting: 6.2 PIESCI 2023 - Tablas.xlsx
 extracting: 6.2.1 PIESCI 2023 - Eventos.docx
  inflating: 6.3 Direcci├│n Nacional de Gesti├│n Universitaria 2023 - Anuario Estad├нsticas Universitarias.doc
 extracting: 6.4 SSFTE 2023.docx
 extracting: 6.5 Programa de Becas Estrat├йgicas Manuel Belgrano 2023 - Anexo.xlsx
 extracting: 6.5 Programa de Becas Estrat├йgicas Manuel Belgrano 2023.docx
 extracting: Anexo_Aspectos Metodol├│gicos 2023.docx

Supongamos que queremos extrer del Anexo_Aspectos Metodológicos la tabla que referencia nombres de universidades (descargar el word y observar donde se encuentra)

In [34]:
#se instala el módulo
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.0.3)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 4.8 MB/s eta 0:00:00a 0:00:01
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [35]:
#se carga la librería
import docx

from docx import Document


import pandas as pd

In [36]:
#se lee el word
document = Document('/content/Anexo_Aspectos Metodol├│gicos 2023.docx')

In [37]:
df1=document.tables[5] #debo prestar atención cual es la posición del objeto (tabla) que quiero extraer
df1

In [38]:
data = [[cell.text for cell in row.cells] for row in df1.rows]
df = pd.DataFrame(data)
df

,0,1,2
0,2.5. Abreviaturas de Instituciones Universitar...,2.5. Abreviaturas de Instituciones Universitar...,2.5. Abreviaturas de Instituciones Universitar...
1,a. Universidades Nacionales de Gestión Estatal,Sigla,Nombre Corto
2,Universidad Nacional del Alto Uruguay,UNAU,Alto Uruguay
3,Universidad Nacional de las Artes,UNA,Artes
4,Universidad Nacional Arturo Jauretche,UNAJ,Arturo Jauretche
5,Universidad Nacional de Avellaneda,UNDAV,Avellaneda
6,Universidad de Buenos Aires,UBA,Buenos Aires
7,Universidad Nacional de Catamarca,UNCA,Catamarca
8,Universidad Nacional del Centro de la Provinci...,UNICEN,Centro de la PBA
9,Universidad Nacional del Chaco Austral,UNCAUS,Chaco Austral
10,Universidad Nacional de Chilecito,UNDEC,Chilecito
11,Universidad Nacional del Comahue,UNCOMA,Comahue
12,Universidad Nacional de los Comechingones,UNLC,Comechingones
13,Universidad Nacional de Córdoba,UNC,Córdoba
14,Universidad Nacional de Cuyo,UNCU,Cuyo
15,Universidad Nacional de la Defensa,UNDEF,Defensa
16,Universidad Nacional de Entre Ríos,UNER,Entre Ríos
17,Universidad Nacional de Formosa,UNF,Formosa
18,Universidad Nacional de General Sarmiento,UNGS,Gral. Sarmiento
19,Universidad Nacional Guillermo Brown,UNAB,Guillermo Brown
20,Universidad Nacional de Hurlingham,UNHAUR,Hurlingham
21,Universidad Nacional José C. Paz,UNPAZ,José C. Paz
22,Universidad Nacional de Jujuy,UNJU,Jujuy
23,Universidad Nacional de La Matanza,UNLM,La Matanza
24,Universidad Nacional de La Pampa,UNLPAM,La Pampa
25,Universidad Nacional de La Plata,UNLP,La Plata
26,Universidad Nacional de La Rioja,UNLR,La Rioja
27,Universidad Nacional de Lanús,UNLA,Lanús
28,Universidad Nacional del Litoral,UNL,Litoral
29,Universidad Nacional de Lomas de Zamora,UNLZ,Lomas de Zamora
30,Universidad Nacional de Luján,UNLU,Luján
31,Universidad Nacional de Mar del Plata,UNMDP,Mar del Plata
32,Universidad Nacional de Misiones,UNAM,Misiones
33,Universidad Nacional de Moreno,UNM,Moreno
34,Universidad Nacional del Nordeste,UNNE,Nordeste
35,Universidad Nacional del Noroeste de la Provin...,UNNOBA,Noroeste de la PBA
36,Universidad Nacional del Oeste,UNO,Oeste
37,Universidad Nacional de la Patagonia Austral,UNPA,Patagonia Austral
38,Universidad Nacional de la Patagonia San Juan ...,UNPSJB,Patagonia S. J. Bosco
39,Universidad Pedagógica Nacional,UNIPE,Pedagógica
40,Universidad Nacional de Quilmes,UNQ,Quilmes
41,Universidad Nacional de Rafaela,UNRAF,Rafaela
42,Universidad Nacional de Río Cuarto,UNRC,Río Cuarto
43,Universidad Nacional de Río Negro,UNRN,Río Negro
44,Universidad Nacional de Rosario,UNR,Rosario
45,Universidad Nacional de Salta,UNSA,Salta
46,Universidad Nacional de San Antonio de Areco,UNSADA,San Antonio de Areco
47,Universidad Nacional de San Juan,UNSJ,San Juan
48,Universidad Nacional de San Luis,UNSL,San Luis
49,Universidad Nacional de San Martín,UNSAM,San Martín
50,Universidad Nacional de Santiago del Estero,UNSE,Santiago del Estero
51,Universidad Nacional Raúl Scalabrini Ortiz,UNSO,Scalabrini Ortiz
52,Universidad Nacional del Sur,UNS,Sur
53,Universidad Tecnológica Nacional,UTN,Tecnológica Nacional
54,"Universidad Nacional de Tierra del Fuego, Antá...",UNTDF,Tierra del Fuego
55,Universidad Nacional de Tres de Febrero,UNTREF,Tres de Febrero
56,Universidad Nacional de Tucumán,UNT,Tucumán
57,Universidad Nacional de Villa María,UNVM,Villa María
58,Universidad Nacional de Villa Mercedes,UNViMe,Villa Mercedes

In [39]:
#borramos la fila 0
df.drop([0], axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)
df

,0,1,2
0,a. Universidades Nacionales de Gestión Estatal,Sigla,Nombre Corto
1,Universidad Nacional del Alto Uruguay,UNAU,Alto Uruguay
2,Universidad Nacional de las Artes,UNA,Artes
3,Universidad Nacional Arturo Jauretche,UNAJ,Arturo Jauretche
4,Universidad Nacional de Avellaneda,UNDAV,Avellaneda
5,Universidad de Buenos Aires,UBA,Buenos Aires
6,Universidad Nacional de Catamarca,UNCA,Catamarca
7,Universidad Nacional del Centro de la Provinci...,UNICEN,Centro de la PBA
8,Universidad Nacional del Chaco Austral,UNCAUS,Chaco Austral
9,Universidad Nacional de Chilecito,UNDEC,Chilecito
10,Universidad Nacional del Comahue,UNCOMA,Comahue
11,Universidad Nacional de los Comechingones,UNLC,Comechingones
12,Universidad Nacional de Córdoba,UNC,Córdoba
13,Universidad Nacional de Cuyo,UNCU,Cuyo
14,Universidad Nacional de la Defensa,UNDEF,Defensa
15,Universidad Nacional de Entre Ríos,UNER,Entre Ríos
16,Universidad Nacional de Formosa,UNF,Formosa
17,Universidad Nacional de General Sarmiento,UNGS,Gral. Sarmiento
18,Universidad Nacional Guillermo Brown,UNAB,Guillermo Brown
19,Universidad Nacional de Hurlingham,UNHAUR,Hurlingham
20,Universidad Nacional José C. Paz,UNPAZ,José C. Paz
21,Universidad Nacional de Jujuy,UNJU,Jujuy
22,Universidad Nacional de La Matanza,UNLM,La Matanza
23,Universidad Nacional de La Pampa,UNLPAM,La Pampa
24,Universidad Nacional de La Plata,UNLP,La Plata
25,Universidad Nacional de La Rioja,UNLR,La Rioja
26,Universidad Nacional de Lanús,UNLA,Lanús
27,Universidad Nacional del Litoral,UNL,Litoral
28,Universidad Nacional de Lomas de Zamora,UNLZ,Lomas de Zamora
29,Universidad Nacional de Luján,UNLU,Luján
30,Universidad Nacional de Mar del Plata,UNMDP,Mar del Plata
31,Universidad Nacional de Misiones,UNAM,Misiones
32,Universidad Nacional de Moreno,UNM,Moreno
33,Universidad Nacional del Nordeste,UNNE,Nordeste
34,Universidad Nacional del Noroeste de la Provin...,UNNOBA,Noroeste de la PBA
35,Universidad Nacional del Oeste,UNO,Oeste
36,Universidad Nacional de la Patagonia Austral,UNPA,Patagonia Austral
37,Universidad Nacional de la Patagonia San Juan ...,UNPSJB,Patagonia S. J. Bosco
38,Universidad Pedagógica Nacional,UNIPE,Pedagógica
39,Universidad Nacional de Quilmes,UNQ,Quilmes
40,Universidad Nacional de Rafaela,UNRAF,Rafaela
41,Universidad Nacional de Río Cuarto,UNRC,Río Cuarto
42,Universidad Nacional de Río Negro,UNRN,Río Negro
43,Universidad Nacional de Rosario,UNR,Rosario
44,Universidad Nacional de Salta,UNSA,Salta
45,Universidad Nacional de San Antonio de Areco,UNSADA,San Antonio de Areco
46,Universidad Nacional de San Juan,UNSJ,San Juan
47,Universidad Nacional de San Luis,UNSL,San Luis
48,Universidad Nacional de San Martín,UNSAM,San Martín
49,Universidad Nacional de Santiago del Estero,UNSE,Santiago del Estero
50,Universidad Nacional Raúl Scalabrini Ortiz,UNSO,Scalabrini Ortiz
51,Universidad Nacional del Sur,UNS,Sur
52,Universidad Tecnológica Nacional,UTN,Tecnológica Nacional
53,"Universidad Nacional de Tierra del Fuego, Antá...",UNTDF,Tierra del Fuego
54,Universidad Nacional de Tres de Febrero,UNTREF,Tres de Febrero
55,Universidad Nacional de Tucumán,UNT,Tucumán
56,Universidad Nacional de Villa María,UNVM,Villa María
57,Universidad Nacional de Villa Mercedes,UNViMe,Villa Mercedes

In [40]:
#utilizar fila 0 como encabezados de columnas
df.columns=df.iloc[0]
df=df.drop(df.index[0])
df.reset_index(drop=True, inplace=True)

In [41]:
df

,a. Universidades Nacionales de Gestión Estatal,Sigla,Nombre Corto
0,Universidad Nacional del Alto Uruguay,UNAU,Alto Uruguay
1,Universidad Nacional de las Artes,UNA,Artes
2,Universidad Nacional Arturo Jauretche,UNAJ,Arturo Jauretche
3,Universidad Nacional de Avellaneda,UNDAV,Avellaneda
4,Universidad de Buenos Aires,UBA,Buenos Aires
5,Universidad Nacional de Catamarca,UNCA,Catamarca
6,Universidad Nacional del Centro de la Provinci...,UNICEN,Centro de la PBA
7,Universidad Nacional del Chaco Austral,UNCAUS,Chaco Austral
8,Universidad Nacional de Chilecito,UNDEC,Chilecito
9,Universidad Nacional del Comahue,UNCOMA,Comahue
10,Universidad Nacional de los Comechingones,UNLC,Comechingones
11,Universidad Nacional de Córdoba,UNC,Córdoba
12,Universidad Nacional de Cuyo,UNCU,Cuyo
13,Universidad Nacional de la Defensa,UNDEF,Defensa
14,Universidad Nacional de Entre Ríos,UNER,Entre Ríos
15,Universidad Nacional de Formosa,UNF,Formosa
16,Universidad Nacional de General Sarmiento,UNGS,Gral. Sarmiento
17,Universidad Nacional Guillermo Brown,UNAB,Guillermo Brown
18,Universidad Nacional de Hurlingham,UNHAUR,Hurlingham
19,Universidad Nacional José C. Paz,UNPAZ,José C. Paz
20,Universidad Nacional de Jujuy,UNJU,Jujuy
21,Universidad Nacional de La Matanza,UNLM,La Matanza
22,Universidad Nacional de La Pampa,UNLPAM,La Pampa
23,Universidad Nacional de La Plata,UNLP,La Plata
24,Universidad Nacional de La Rioja,UNLR,La Rioja
25,Universidad Nacional de Lanús,UNLA,Lanús
26,Universidad Nacional del Litoral,UNL,Litoral
27,Universidad Nacional de Lomas de Zamora,UNLZ,Lomas de Zamora
28,Universidad Nacional de Luján,UNLU,Luján
29,Universidad Nacional de Mar del Plata,UNMDP,Mar del Plata
30,Universidad Nacional de Misiones,UNAM,Misiones
31,Universidad Nacional de Moreno,UNM,Moreno
32,Universidad Nacional del Nordeste,UNNE,Nordeste
33,Universidad Nacional del Noroeste de la Provin...,UNNOBA,Noroeste de la PBA
34,Universidad Nacional del Oeste,UNO,Oeste
35,Universidad Nacional de la Patagonia Austral,UNPA,Patagonia Austral
36,Universidad Nacional de la Patagonia San Juan ...,UNPSJB,Patagonia S. J. Bosco
37,Universidad Pedagógica Nacional,UNIPE,Pedagógica
38,Universidad Nacional de Quilmes,UNQ,Quilmes
39,Universidad Nacional de Rafaela,UNRAF,Rafaela
40,Universidad Nacional de Río Cuarto,UNRC,Río Cuarto
41,Universidad Nacional de Río Negro,UNRN,Río Negro
42,Universidad Nacional de Rosario,UNR,Rosario
43,Universidad Nacional de Salta,UNSA,Salta
44,Universidad Nacional de San Antonio de Areco,UNSADA,San Antonio de Areco
45,Universidad Nacional de San Juan,UNSJ,San Juan
46,Universidad Nacional de San Luis,UNSL,San Luis
47,Universidad Nacional de San Martín,UNSAM,San Martín
48,Universidad Nacional de Santiago del Estero,UNSE,Santiago del Estero
49,Universidad Nacional Raúl Scalabrini Ortiz,UNSO,Scalabrini Ortiz
50,Universidad Nacional del Sur,UNS,Sur
51,Universidad Tecnológica Nacional,UTN,Tecnológica Nacional
52,"Universidad Nacional de Tierra del Fuego, Antá...",UNTDF,Tierra del Fuego
53,Universidad Nacional de Tres de Febrero,UNTREF,Tres de Febrero
54,Universidad Nacional de Tucumán,UNT,Tucumán
55,Universidad Nacional de Villa María,UNVM,Villa María
56,Universidad Nacional de Villa Mercedes,UNViMe,Villa Mercedes